name: Publish package to the Maven Central Repository and GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Set up java with maven cache
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      #import the secret key
      - name: Set up Apache Maven Central
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
          cache: 'maven'
      #Publicamos en maven
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -X
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
