name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 11
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      #import the secret key
      - name: Set up Apache Maven GitHub
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Env var that holds the key's passphrase
          cache: 'maven'
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -P Github -Darguments=-Dgpg.passphrase=${{ secrets.SIGN_KEY_PASS }} -X
        env:
          GITHUB_USERNAME: ${{ secrets.USER_NAME }}
          GITHUB_PASSWORD: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}
